language: erlang

sudo: required

# Default is 16.04 (xenial) but 18.04 is needed to get TLS 1.3 working
dist: bionic

services:
  - docker

notifications:
  email: false

otp_release:
  - 23.0
  - 22.3
  - 22.1
  - 21.2
  - 20.3.8

install:
  - sudo apt-get install -qq --no-install-recommends faketime
  - sudo docker info
  - git clone https://github.com/erlang/rebar3.git && cd rebar3 && git checkout 3.13.1 && ./bootstrap && sudo mv rebar3 /usr/local/bin/ && cd ..
  - git clone https://github.com/inaka/elvis.git && cd elvis && rebar3 escriptize && sudo cp _build/default/bin/elvis /usr/bin && cd ..

script:
  - make elvis

  - make clean
  - make compile
  - make xref
  - make dialyzer

  # - make edoc

  - make test
  - make cover

after_success:
  - make coveralls
