name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: |
          sudo apt update
          sudo apt install emacs-nox
      - name: Install Erlang/OTP and rebar3
        uses: erlef/setup-beam@v1
        with:
          otp-version: '25.3.2.18'
          rebar3-version: '3.24.0'
      - name: Run erlang-formatter
        run: |
          rebar3 fmt
          status="$(git status --untracked-file=no --porcelain)"
          if [ ! -z "$status" ]; \
          then \
             echo "Error: Please format the following files (e.g. run 'rebar3 fmt')"; \
             echo "$status"; \
             exit 1; \
          fi

  ci:
    strategy:
      matrix:
        include:
          - otp-version: '25.3.2.18'
            rebar3-version: '3.24.0'
          - otp-version: '24.3.4.17'
            rebar3-version: '3.17.0'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Hex packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/rebar3/hex/hexpm/packages
          key: ${{ runner.os }}-${{ matrix.otp-version }}-hex-${{ hashFiles('**/rebar.lock') }}

      - name: Cache Dialyzer PLTs
        uses: actions/cache@v4
        with:
          path: ~/.cache/rebar3/rebar3_*_plt
          key: ${{ runner.os }}-${{ matrix.otp-version }}-dialyzer-${{ hashFiles('**/rebar.config') }}
          restore-keys: ${{ runner.os }}-${{ matrix.otp-version }}-dialyzer-

      - name: Install Erlang/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          rebar3-version: ${{ matrix.rebar3-version }}

      - name: Install elvis
        run: |
          git clone --depth 1 --branch 1.1.0 https://github.com/inaka/elvis.git
          cd elvis && rebar3 escriptize && sudo cp _build/default/bin/elvis /usr/local/bin/

      - name: Install faketime
        run: |
          sudo apt update
          sudo apt install -yy --no-install-recommends faketime

      - name: Build and test
        run: |
          make compile
          make ut ct-tcp
          make cover

      - name: Run checks
        run: |
          make elvis
          make xref
          make dialyzer

      - name: Generate docs
        run: |
          make edoc
          git diff --exit-code ./doc || echo "** Please commit your changes from 'make edoc' **"
