name: Redis compatibility testing
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  redis-comp:
    strategy:
      fail-fast: false
      matrix:
        include:
          - redis-version: '7.2.4'  # Last open source release
            test-target: ct
          - redis-version: '7.0.4'
            test-target: ct
          - redis-version: '6.2.7'
            test-target: ct
          - redis-version: '6.0.16'
            test-target: ct
          - redis-version: '5.0.14'
            test-target: ct-tcp
          - redis-version: '4.0.14'
            test-target: ct-tcp
          - redis-version: '3.2.12'
            test-target: ct-tcp
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Hex packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/rebar3/hex/hexpm/packages
          key: ${{ runner.os }}-hex-${{ hashFiles('**/rebar.lock') }}
          restore-keys: ${{ runner.os }}-hex-

      - name: Install Erlang/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: '25.3.2.18'
          rebar3-version: '3.24.0'

      - name: Install faketime
        run: |
          sudo apt update
          sudo apt install -yy --no-install-recommends faketime

      - name: Build
        run: make compile

      - name: Test
        run: |
          REDIS_VERSION=${{ matrix.redis-version }} make ${{ matrix.test-target }}
